Fix bug in transposed convolution lowering to affine nest.
polymage-labs/mlir-hlo pull request #8
Opened 2022-06-27 11:39 UTC by akshaybaviskar

Current lowering lowers `lmhlo.convolution` to affine loop nest representing the transposed convolution which is semantically incorrect. 
Fix: Lower the combination of reverse op and `lmhlo.convolution` to affine nest.

2022-06-27 11:55 UTC, bondhugula reviewed
Thanks for the quick turnaround on this. An organization comment below.

2022-06-27 11:56 UTC, bondhugula commented on tests/lhlo-legalize-to-affine.mlir
> +    lmhlo.convolution(%input, %reversed_filter, %output)
Can you also add a negative test where a filter that is from a reversal isn't lowered to affine this way?

2022-06-27 22:50 UTC, bondhugula requested changes
Several changes to make on the check here.

2022-06-27 22:50 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +/// convolutions to affine loop nest. This function handles only transposed
Nit: `... a affine loop nest`

2022-06-27 22:50 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
>  ///   Input shape is N spatial_dims(I_H I_W) C_in
"is" or "should be"?

2022-06-27 22:50 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +  static Value getNonReversedKernel(Value reversed_kernel,
`getAndEraseReverseKernel`?

2022-06-27 22:50 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +      if (genericOp) {
Always use early exit. It will reduce the indent of the entire block of 50 lines below and be more readable. Please see:
https://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code

2022-06-27 22:50 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +    auto kernelAlloc = reversed_kernel.getDefiningOp<memref::AllocOp>();
This isn't really right or needed: the kernel may not be alloc'ed in the function. It might just be a function argument or the result of another op. This whole logic to get the defining op and look at its users isn't meaningful. You don't need the loop or check of its uses. Instead look at the op defining the operand of convolution filter operand. Pass that here and you won't need the check at line 325.

2022-06-27 22:50 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +            dyn_cast<linalg::YieldOp>(genericOpBlock->getOperations().front());
You don't need `getOperations()` -- just use `front()` on the block. In fact, in this case, you can just use `getTerminator`.

2022-06-27 22:50 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +        if (genericOpBlock->getOperations().size() != 1)
Please don't use size() on a list -- this will be O(N). Instead, use `llvm::hasSingleElement` which will be O(1).

2022-06-27 22:50 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +                          kernelAlloc.memref().getUsers().end()) == 2)
This is all unnecessary and even quite inefficient -- checking for distances in linked lists is O(N) and this check could have been written more efficiently to be O(1). (For eg. hasOneUse or hasTwoUses().) But anyway you don't even need to look at the user list.

2022-06-28 03:37 UTC, akshaybaviskar commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +    auto kernelAlloc = reversed_kernel.getDefiningOp<memref::AllocOp>();
> Instead look at the op defining the operand of convolution filter operand.

This is in fact the op defining the operand of convolution filter operand.
Is there a way I can get to the `Linalg.generic` op using this operand?

2022-06-28 04:33 UTC, akshaybaviskar commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +                          kernelAlloc.memref().getUsers().end()) == 2)
Oh, thanks. I missed this point. I am checking for twoUses now. Please review.

2022-07-24 12:43 UTC, akshaybaviskar commented
Handled in https://github.com/polymage-labs/mlir-hlo/pull/9. This PR is not required now.

2022-07-24 12:43 UTC, closed without merging