Changes to run transpose convolution on tensor core.
polymage-labs/mlir-hlo pull request #9
Opened 2022-07-06 12:18 UTC by akshaybaviskar

This PR implements two changes.

A. [Fix CPU lowering for transposed convolution.](https://github.com/polymage-labs/mlir-hlo/pull/9/commits/380681e3f1f0109b9e31e8addef5b48344a65b3f):
  1. Initialize output to zero.
  2. Lower combination of reverse op (implemented using linalg::GenericOp)  and lmhlo.convolution op which together represent the transposed convolution.

B. [Add transposed convolution lowering for GPU CUDA cores and tensor cores.](https://github.com/polymage-labs/mlir-hlo/pull/9/commits/a2bc2ddd49e424c740fd32f6bcfe81dbc9d0c0b8):
  1. Add 'target' option to lhlo-legalize-to-affine pass to differentiate  between CPU, GPU CUDA cores and GPU tensor cores.
  2. Add transposed convolution lowering for GPUs where we express transposed  convolution as matrix multiplication of specially packed input and kernel  to enable its execution on GPU tensor cores.
  3. Add 'trans-conv-tile-size' option to pass to enable tile size selection  for the tiles of matrix multiplication representing the transposed  convolution.

2022-07-18 06:55 UTC, bondhugula commented on tests/lhlo-legalize-to-affine.mlir
> +// RUN: mlir-hlo-opt -lhlo-legalize-to-affine -split-input-file %s -o - | FileCheck %s
We can't unconditionally generate a GPU lowering from an lmhlo op. We should be looking at the target information in some way. (`ModuleOp` for eg. has this information but we don't yet have it op-wise on lmhlo ops.)

2022-07-18 07:03 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +    AffineForOp firstOuterForOp;
Tile sizes used should be clearly defined and exposed from this lowering.

2022-07-19 16:08 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +    for (unsigned i = 0; i <= 2; i += 2) {
Nit: `i < 3`

2022-07-19 16:08 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +  static void loadKernelTile(PatternRewriter &rewriter, Location loc,
Doc comment.

2022-07-19 16:09 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +  static void performMatMul(PatternRewriter &rewriter, Location loc,
All methods (including local ones) should have doc comments.

2022-07-19 16:10 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +        (((d[0] + d[2]) * s[0] + (d[1] + d[3]) % s[0]).floorDiv(s[1] * s[2])) *
Please use code comments to write the high-level math form of these expressions.

2022-07-19 16:11 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +    rewriter.setInsertionPointAfter(firstForOp);
Refactor any really long methods to shorter logically complete pieces where possible.

2022-07-19 16:15 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +    SmallVector<Value> matMulIvs;
`Value, 3`.

2022-07-19 16:15 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +    SmallVector<Value> tiledMatMulIvs;
Likewise.

2022-07-19 16:15 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +    // Multiply kernel and input elements and accumulate to the output
We need more code comments here and in general below/above.

2022-07-19 16:15 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +  static void loadInputTile(PatternRewriter &rewriter, Location loc,
Doc comment.

2022-07-19 16:15 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +    finalOutOperands.push_back(rewriter.create<arith::ConstantIndexOp>(loc, 4));
You can use a 

`using mlir::arith::ConstantIndexOp` at the top to reduce verbosity.

2022-07-19 16:15 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +                                   finalOutOperands);
clagn-format please.

`git clang-format origin/polymage`

2022-07-21 07:34 UTC, bondhugula reviewed
The code is significantly better organized now - thanks! Some minor comments.

2022-07-21 07:34 UTC, bondhugula commented on include/mlir-hlo/Dialect/mhlo/transforms/lmhlo_passes.td
> +        "transConvMatmulTileSizes", "trans-conv-matmul-tile-sizes", "uint64_t",
`trans-conv-tile-sizes`?

2022-07-21 07:34 UTC, bondhugula commented on include/mlir-hlo/Dialect/mhlo/transforms/lmhlo_passes.td
> +        "List of outer tile sizes followed by inner tile sizes(in the order "
Leave space before `(`.

2022-07-21 07:34 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +      return failure();
Drop unrelated changes.

2022-07-21 07:34 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +      if (genericOp.outputs().size() != 1)
You can combine into one `if`.

2022-07-21 07:34 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +      if (!llvm::hasSingleElement(genericOpBlock->getOperations()))
`getOperations` isn't needed I believe. You can just use hasSingleElement on the block.

2022-07-21 07:34 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +      // Erase `genericOp` if it's output is being used at only two places --
at two or fewer places?

2022-07-21 07:34 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +  /// Here we assume the `input` to be padded with zeros and thus insert the
Use full width. Reflow.

2022-07-21 07:34 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +                            SmallVector<AffineExpr> &s) {
d -> dims
s -> symbols
?

2022-07-21 07:35 UTC, bondhugula commented
Please make sure to squash commits into the logical ones desired before merging.

2022-07-21 09:06 UTC, akshaybaviskar commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +                            SmallVector<AffineExpr> &s) {
I think d and s helps the affine expressions declared below to be smaller, also this is close to the representation in IR.

2022-07-21 09:57 UTC, bondhugula approved these changes

2022-07-21 09:57 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +  /// matrix  multiplication of input and kernel. Further, the IR is written in
```We express the transpose convolution using matrix multiplications by packing the weights and input in a specific manner. The matrix multiplications are between the specially packed weights and inputs. ``` 
You also need to mention that there is a 4-way decomposition of the weights on-the-fly and it's a summation of independent matmuls that yields the result of the convolution in a tiled manner.

2022-07-21 09:57 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +  ///  3. The tiles are loaded from global memory to shared memory.
We are missing a depiction of the overall structure of the loop nest that we would lower to. The test case CHECK lines pretty much capture it but it doesn't have information on what's batches, height, width, channels, and kernel.  You need to just outline the loop nesting while indicating what the IVs correspond to. For eg:
```
affine.for %b = ... 
  affine.for ...
    ...
     // Copy/packing nest for ... input
     ...
  ...
```

2022-07-21 11:25 UTC, bondhugula commented on tests/lhlo-legalize-to-affine.mlir
> +// CHECK-NEXT:              affine.store %3, %arg2[symbol(%c0), (((%arg5 + %arg3) * symbol(%c4) + (%arg6 + %arg4) mod symbol(%c4)) floordiv (symbol(%c2) * symbol(%c118))) * symbol(%c2) + ((%arg6 + %a
No numbered SSA values should be matched in CHECK lines.

2022-07-21 17:30 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +#include "mlir/IR/Value.h"
You don't need this include.

2022-07-21 17:32 UTC, bondhugula requested changes

2022-07-21 17:32 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +      curKernelEle = rewriter.create<arith::TruncFOp>(loc, curKernelEle,
Nit: `curKernelElt`

2022-07-21 17:32 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +                SmallVector<AffineExpr> &s) {
Please document `d` and `s`.

2022-07-21 17:32 UTC, bondhugula commented on tests/lhlo-legalize-to-affine.mlir
> +// RUN: mlir-hlo-opt -lhlo-legalize-to-affine="target=2" -split-input-file %s -o - | FileCheck %s -check-prefix=TRANSCONV-TENSOR
Please don't use numbers like these -- they are unreadable. Use strings.

2022-07-21 18:42 UTC, akshaybaviskar commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +  ///  3. The tiles are loaded from global memory to shared memory.
updated, please check.

2022-07-22 01:33 UTC, bondhugula approved these changes
LGTM - minor comments.

2022-07-22 01:33 UTC, bondhugula commented on include/mlir-hlo/Dialect/mhlo/transforms/lmhlo_passes.td
> +           "Specifies the target; default target is `cpu`. For GPU CUDA Cores "
Cores -> cores

2022-07-22 01:33 UTC, bondhugula commented on include/mlir-hlo/Dialect/mhlo/transforms/lmhlo_passes.td
> +           "set it to `gpuCuda`. For GPU Tensor Cores set it to `gpuTensor`.">,
gpuCuda -> gpu_cuda

Lower case and snake case for all cmd-line pass options.

Tensor Cores -> tensor cores

gpuTensor -> gpu_tensor

2022-07-22 01:33 UTC, bondhugula commented on include/mlir-hlo/Dialect/mhlo/transforms/lmhlo_passes.td
> +           "set it to `gpuCuda`. For GPU Tensor Cores set it to `gpuTensor`.">,
set it to -> set to

2022-07-22 03:00 UTC, bondhugula approved these changes

2022-07-22 03:00 UTC, bondhugula commented on tests/lhlo-legalize-to-affine.mlir
> +    ^bb0(%arg0: f32 loc(unknown), %arg1: f32 loc(unknown)):  // no predecessors
You can drop `loc(unknown)` everywhere from these tests. They aren't needed for testing.

2022-07-22 15:04 UTC, bondhugula approved these changes

2022-07-22 15:04 UTC, bondhugula commented on lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
> +    for (unsigned i = 0; i < outputShape.size(); i++) {
Use `i = 0, e = ...; i < e; ...` to prevent repeated evaluation of `size()`.

2022-07-22 15:04 UTC, bondhugula commented on tests/lhlo-legalize-to-affine.mlir
> +// CHECK-NEXT:   affine.for %[[O_N:.*]] = 0 to 1 {
Good catch!

2022-07-24 12:07 UTC, merged